version: "3.9"

services:
  api-cpu:
    build:
      context: .
      dockerfile: ops/docker/Dockerfile.cpu
    image: astroclassify:cpu
    restart: unless-stopped
    environment:
      LOGLEVEL: INFO
      PROMETHEUS_MULTIPROC_DIR: /tmp/prom-multi
    ports:
      - "8000:8000"

  api-gpu:
    profiles: ["gpu"]
    build:
      context: .
      dockerfile: ops/docker/Dockerfile.gpu
    image: astroclassify:gpu
    restart: unless-stopped
    environment:
      LOGLEVEL: INFO
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      PROMETHEUS_MULTIPROC_DIR: /tmp/prom-multi
    ports:
      - "8001:8000"
    device_requests:
      - driver: nvidia
        count: 1
        capabilities: ["gpu"]
